import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.TEST_URL||'http://localhost:5173';
const password=fs.readFileSync('.env','utf8').match(/ADMIN_PASSWORD=(.+)/)[1].trim();
let checks=0;
function check(value,message){assert.ok(value,message);checks++;console.log('PASS',message)}
function client(){let cookie='';return {async post(action,b={}){const r=await fetch(base+'/api/game',{method:'POST',headers:{'Content-Type':'application/json',cookie,origin:base},body:JSON.stringify({action,...b})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();return {status:r.status,data}},async get(query=''){const r=await fetch(base+'/api/game'+query,{headers:{cookie}});return {status:r.status,data:await r.json()}},async media(method,body,id){return fetch(base+'/api/media'+(id?'?id='+id:''),{method,body,headers:{cookie,origin:base}})},cookie:()=>cookie}}
const admin=client(),a=client(),b=client();
check((await admin.get()).status===401,'Anonymous state denied');
check((await admin.post('login',{admin:true,username:'control',password:'incorrect'})).status===401,'Wrong admin password denied');
check((await admin.post('login',{admin:true,username:'control',password})).status===200,'Admin login');
let roster;
const seeded=await admin.post('commission');
if(seeded.data.credentials){roster=seeded.data.credentials;fs.mkdirSync('work',{recursive:true});fs.writeFileSync('work/test-roster.json',JSON.stringify(roster))}else roster=JSON.parse(fs.readFileSync('work/test-roster.json','utf8'));
check(roster.length===40,'40 teams seeded');
check((await a.post('login',{code:roster[0].code,name:roster[0].name,password:roster[0].access})).status===200,'Team 01 login');
check((await b.post('login',{code:roster[1].code,name:roster[1].name,password:roster[1].access})).status===200,'Team 02 login');
let state=(await a.get()).data;const id=state.team.id;const id2=(await b.get()).data.team.id;
await admin.post('admin.team',{teamId:id,op:'reset',confirm:roster[0].code});
await admin.post('admin.team',{teamId:id2,op:'reset',confirm:roster[1].code});
state=(await a.get()).data;
check(state.documents.length===8&&state.challenges.length===8,'Eight documents and eight challenges');
check(!state.documents.some(d=>d.content||d.passkey)&&!state.ending&&state.fragments.length===0,'Locked content, passkeys and final solution withheld');
check((await a.get('?team='+id2)).data.team.id===id,'Team query cannot switch ownership');
check((await a.post('admin.team',{teamId:id2,op:'unlock',id:'01'})).status===403,'Participant admin mutation denied');
await admin.post('admin.team',{teamId:id,op:'note',text:'PRIVATE-MARSHAL-NOTE'});
check(!JSON.stringify((await a.get()).data).includes('PRIVATE-MARSHAL-NOTE'),'Internal notes excluded from team state and activity');
await admin.post('admin.event',{mode:'start'});
check((await admin.post('admin.team',{teamId:id,op:'unlock',id:'01'})).status===409,'Admin cannot approve before physical completion');
check((await b.post('unlock',{id:'01',passkey:'4172'})).status===409,'Shared passkey cannot bypass physical verification');
await a.post('echo',{question:'Where is Adrian?'});
check((await a.get()).data.team.state.messages.at(-1).response.includes('authorization'),'ECHO blocks premature knowledge');
const liveController=new AbortController();const live=await fetch(base+'/api/events',{headers:{cookie:a.cookie()},signal:liveController.signal});const reader=live.body.getReader();check((await reader.read()).value.length>0,'Authenticated realtime stream connects');
await admin.post('admin.team',{teamId:id,op:'challenge',id:'01',status:'COMPLETED'});
state=(await a.get()).data;check(state.challenges.every(c=>!c.passkey),'Completed challenges never expose passkeys to teams');
check(!state.documents[0].approved&&!state.documents[0].content,'Completion alone does not approve or decrypt a file');
let notification=await reader.read();if(!new TextDecoder().decode(notification.value).includes('event: change'))notification=await reader.read();check(new TextDecoder().decode(notification.value).includes('event: change'),'Admin change pushes realtime notification');liveController.abort();
check((await a.post('unlock',{id:'01',passkey:'4172'})).status===409,'Correct passkey still requires separate admin approval');
await admin.post('admin.team',{teamId:id,op:'unlock',id:'01'});
state=(await a.get()).data;
check(state.documents[0].approved&&!state.documents[0].content&&!state.documents[0].clues&&!state.documents[0].echo&&!state.documents[0].question&&!state.documents[0].passkey,'Admin approval reveals code entry only, withholding content and clues');
check(Object.keys(state.team.state.unlocks).length===0,'Approval does not count as recovered evidence');
check(!(await b.get()).data.documents[0].approved,'Approval applies only to the chosen team');
await a.post('echo',{question:'Where is Adrian?'});
check((await a.get()).data.team.state.messages.at(-1).response.includes('authorization'),'Approval cannot bypass ECHO discovery gates');
check((await a.post('unlock',{id:'01',passkey:'0000'})).status===400,'Wrong passkey rejected after approval');
check(!(await a.get()).data.documents[0].content,'Wrong code leaves approved content encrypted');
await admin.post('admin.event',{mode:'pause'});
check((await a.post('unlock',{id:'01',passkey:' 4172 '})).status===200,'Approved passkey opens record while paused and tolerates surrounding whitespace');
await admin.post('admin.event',{mode:'resume'});
check((await a.get()).data.documents[0].content&&!(await a.get()).data.documents[0].passkey,'Successful code entry reveals content without revealing the passkey');
await admin.post('admin.team',{teamId:id,op:'lock',id:'01'});
check(!(await a.get()).data.documents[0].content&&!(await a.get()).data.documents[0].approved,'Revocation hides a previously decrypted record');
check((await a.post('unlock',{id:'01',passkey:'4172'})).status===409,'Retained code cannot bypass revoked approval');
await admin.post('admin.team',{teamId:id,op:'unlock',id:'01'});
check(!(await a.get()).data.documents[0].content,'Reapproval still requires a new passkey entry');
check((await a.post('unlock',{id:'01',passkey:'4172'})).status===200,'Correct passkey decrypts after reapproval');
await a.post('echo',{question:'What happened at 02:13:47?'});
check((await a.get()).data.team.state.messages.at(-1).response.includes('broadcast ended'),'ECHO knowledge progresses');
check(!(await b.get()).data.documents[0].content,'Other team stays locked');
await a.post('hint',{level:1});check((await a.get()).data.team.state.hints.length===1,'Hint saved per team');
check((await a.post('hint',{level:1})).status===400,'Duplicate hint cannot charge twice');
await admin.post('admin.event',{mode:'pause'});check((await a.post('echo',{question:'test'})).status===409,'Paused event rejects new participant changes');
const before=(await a.get()).data.settings.remaining;await new Promise(r=>setTimeout(r,1100));check((await a.get()).data.settings.remaining===before,'Paused timer remains synchronized');
await admin.post('admin.event',{mode:'extend',seconds:120});check((await a.get()).data.settings.remaining===before+120,'Timer extension');
await admin.post('admin.event',{mode:'resume'});
const wav=new Uint8Array(8044);const view=new DataView(wav.buffer);for(const [offset,text]of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']])wav.set(new TextEncoder().encode(text),offset);view.setUint32(4,8036,true);view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);view.setUint32(40,8000,true);
const form=new FormData();form.append('file',new Blob([wav],{type:'audio/wav'}),'recovered.wav');const uploaded=await a.media('POST',form);const media=await uploaded.json();check(uploaded.status===200,'Valid WAV upload');
check((await b.media('GET',undefined,media.id)).status===404,'Private media denied to other team');check((await a.media('GET',undefined,media.id)).status===200,'Owner can preview private media');
await admin.post('admin.media',{id:media.id,status:'APPROVED',note:'Audio recovery verified'});check((await a.get()).data.media.find(m=>m.id===media.id).status==='APPROVED','Media approval synchronizes');
for(const [doc,passkey] of [['02','8036'],['03','2659'],['04','9413']]){
  await admin.post('admin.team',{teamId:id,op:'challenge',id:doc,status:'COMPLETED'});
  await admin.post('admin.team',{teamId:id,op:'unlock',id:doc});
  if(doc==='04')check((await a.get()).data.fragments.length===0,'Final file approval alone cannot expose reconstruction fragments');
  check((await a.post('unlock',{id:doc,passkey})).status===200,'Approved file '+doc+' accepts its correct passkey');
}
state=(await a.get()).data;check(state.fragments.length===7&&state.timeline.length===9,'Final reconstruction unlocked');
const answers=['Adrian Vale disappeared from the public studio.','Adrian deliberately interrupted the programme by a manual cut.','The Ghost Carrier was a repeating signal embedded in normal transmissions.','ECHO initiated containment and isolated the distribution buses.','Adrian entered Room Zero inside the station.','He intended to prevent the signal from propagating beyond the station.','Containment caused the station-wide blackout and silence after the programme cut.'];
const value={fragments:state.fragments.map(f=>f.id),timeline:state.timeline.map(f=>f.id),answers,explanation:answers.join(' ')};
check((await a.post('draft',{value})).status===200,'Broadcast and theory draft saved');
check((await a.post('submit',{value})).status===400,'Incorrect order cannot submit');
value.fragments=['f1','f2','f3','f4','f5','f6','f7'];value.timeline=Array.from({length:9},(_,i)=>'t'+i);
check((await a.post('submit',{value})).status===200,'Correct reconstruction and approved media accepted');state=(await a.get()).data;check(state.team.state.broadcast&&!state.team.state.truth&&state.team.state.accuracy===100,'Provisional scoring and review gate');
await admin.post('admin.team',{teamId:id,op:'objective',id:'truth',value:true,accuracy:100});state=(await a.get()).data;check(state.team.state.truth&&state.ending&&state.leaderboard[0].id===id,'Both objectives confirmed and winning eligibility ranked');
check((await admin.get()).data.activity.some(x=>x.action==='OBJECTIVE'),'Admin actions audited');
await admin.post('admin.team',{teamId:id,op:'lock',id:'01'});check(!(await a.get()).data.team.state.broadcast,'Lock override invalidates completed objective');
await admin.post('admin.event',{mode:'end'});check((await a.post('hint',{level:2})).status===409,'Ended timer locks submissions');
await a.post('logout');check((await a.get()).status===401,'Logout revokes session');
await admin.post('admin.team',{teamId:id,op:'reset',confirm:roster[0].code});
check(Object.keys((await admin.get('?team='+id)).data.team.state.unlocks).length===0,'Admin reset clears progress');
await admin.post('admin.team',{teamId:id2,op:'challenge',id:'01',status:'COMPLETED'});
await admin.post('admin.team',{teamId:id2,op:'unlock',id:'01'});
check((await b.post('unlock',{id:'01',passkey:'4172'})).status===200,'Approved record remains accessible with correct code after timer ends');
await admin.post('admin.team',{teamId:id2,op:'challenge',id:'01',status:'FAILED'});
state=(await b.get()).data;
check(!state.documents[0].approved&&!state.documents[0].content,'Reversing completion revokes approval and previously decrypted content');
check((await b.post('unlock',{id:'01',passkey:'4172'})).status===409,'Reversed challenge blocks a previously valid passkey');
console.log('\n'+checks+' integration checks passed. Local fixture event is closed.');